### ISSUE TITLE
Canary should more politely handle network-related exceptions, e.g. Errno::ECONNRESET:

### ISSUE THREAD

**Issue by rtyler** [CodeValet/canary#1]
https://sentry.io/codevalet/canary/issues/342765131/

```
Errno::ECONNRESET: Connection reset by peer - connect(2) for "codevalet.io" port 443
  app/canary/jenkins.rb:19:in `rebuiltUrlFor'
    response = HTTParty.get(url)
  app/canary/jenkins.rb:10:in `rebuiltAlpha'
    return self.rebuiltUrlFor('codevalet')
  app/../views/index.haml:27:in `block in singleton class'
    = jenkins.rebuiltAlpha
  app/canary.rb:34:in `block in <class:App>'
    haml :index,
...
(71 additional frame(s) were not displayed)

Errno::ECONNRESET: Failed to open TCP connection to codevalet.io:443 (Connection reset by peer - connect(2) for "codevalet.io" port 443)
  app/canary/jenkins.rb:19:in `rebuiltUrlFor'
    response = HTTParty.get(url)
  app/canary/jenkins.rb:10:in `rebuiltAlpha'
    return self.rebuiltUrlFor('codevalet')
  app/../views/index.haml:27:in `block in singleton class'
    = jenkins.rebuiltAlpha
  app/canary.rb:34:in `block in <class:App>'
    haml :index,
...
(70 additional frame(s) were not displayed)

Errno::ECONNRESET: Failed to open TCP connection to codevalet.io:443 (Connection reset by peer - connect(2) for "codevalet.io" port 443)
```

**Comment by rtyler** [comment]
`Net::OpenTimeout` is another example Canary should handle

https://sentry.io/codevalet/canary/issues/343112687/
