### ISSUE TITLE
Faraday::ConnectionFailed: execution expired

### ISSUE THREAD

**Issue by rtyler** [CodeValet/canary#10]
https://sentry.io/codevalet/canary/issues/346332755/

```
Net::OpenTimeout: execution expired
  app/canary/dao/jenkins.rb:41:in `rebuilt_for'
    response = connection.get(url)
  app/canary/dao/jenkins.rb:28:in `block in rebuilt_ga'
    rebuilt_for('rtyler')
  app/canary/dao/jenkins.rb:27:in `rebuilt_ga'
    return cache.get_or_set('rebuiltGA', :expires_in => CACHE_SECONDS) do
  app/../views/index.haml:34:in `block in singleton class'
    = jenkins.rebuilt_ga
  app/canary.rb:27:in `block in <class:App>'
    haml :index,
...
(69 additional frame(s) were not displayed)

Faraday::ConnectionFailed: execution expired

Faraday::ConnectionFailed: execution expired
```

Looks like we're not treating Faraday issues as expected network issues.

**Comment by rtyler** [comment]
This tends to happen when Canary is hit while an instance is rebooting
